[window]
dimensions = { columns = 100, lines = 25 }

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMonoNL Nerd Font"
bold.family = "JetBrainsMonoNL Nerd Font"
italic.family = "JetBrainsMonoNL Nerd Font"
bold_italic.family = "JetBrainsMonoNL Nerd Font"

size = 12.0

[general]
import = ["tokyo-night.toml"]

[cursor]
style = { shape="Beam", blinking="Always" }
